CREATE TABLE "CashCollection" (
  "id" SERIAL PRIMARY KEY,
  "amount" DECIMAL(14,2) NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "ConcreteNorm" (
  "id" SERIAL PRIMARY KEY,
  "name" TEXT NOT NULL,
  "grade" "CementGrade" NOT NULL,
  "cementKgPerM3" DECIMAL(10,2) NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL
);

CREATE TABLE "HistoricalBagEntry" (
  "id" SERIAL PRIMARY KEY,
  "date" TIMESTAMP(3) NOT NULL,
  "grade" "CementGrade" NOT NULL,
  "producedBags" INTEGER NOT NULL,
  "soldBags" INTEGER NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX "HistoricalBagEntry_date_grade_key" ON "HistoricalBagEntry"("date", "grade");

INSERT INTO "ConcreteNorm" ("name", "grade", "cementKgPerM3", "updatedAt") VALUES
('М100', 'M500', 180, CURRENT_TIMESTAMP), ('М150', 'M500', 220, CURRENT_TIMESTAMP),
('М200', 'M500', 260, CURRENT_TIMESTAMP), ('М250', 'M500', 280, CURRENT_TIMESTAMP),
('М300', 'M500', 320, CURRENT_TIMESTAMP), ('М350', 'M500', 350, CURRENT_TIMESTAMP),
('М400', 'M500', 400, CURRENT_TIMESTAMP), ('М100', 'M600', 160, CURRENT_TIMESTAMP),
('М150', 'M600', 200, CURRENT_TIMESTAMP), ('М200', 'M600', 240, CURRENT_TIMESTAMP),
('М250', 'M600', 260, CURRENT_TIMESTAMP), ('М300', 'M600', 300, CURRENT_TIMESTAMP),
('М350', 'M600', 330, CURRENT_TIMESTAMP), ('М400', 'M600', 380, CURRENT_TIMESTAMP);
