CREATE TYPE "Material" AS ENUM ('SAND', 'GRAVEL');
CREATE TYPE "ExpenseCategory" AS ENUM ('SALARY','RENT','ELECTRICITY','FUEL','REPAIR','PACKAGING','OTHER');
CREATE TYPE "BarrelOperationType" AS ENUM ('RECEIPT','CONSUMPTION');
CREATE TABLE "User" ("id" SERIAL PRIMARY KEY, "telegramId" BIGINT UNIQUE NOT NULL, "name" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "Worker" ("id" SERIAL PRIMARY KEY, "name" TEXT NOT NULL, "phone" TEXT, "position" TEXT NOT NULL, "active" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "Barrel" ("id" INTEGER PRIMARY KEY, "name" TEXT NOT NULL);
CREATE TABLE "Shift" ("id" SERIAL PRIMARY KEY, "date" TIMESTAMP(3) NOT NULL, "bags" INTEGER NOT NULL, "tons" DECIMAL(12,3) NOT NULL, "loadingTons" DECIMAL(12,3) NOT NULL DEFAULT 0, "packagingPay" DECIMAL(14,2) NOT NULL, "loadingPay" DECIMAL(14,2) NOT NULL, "barrelId" INTEGER NOT NULL REFERENCES "Barrel"("id"), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "ShiftWorker" ("shiftId" INTEGER NOT NULL REFERENCES "Shift"("id") ON DELETE CASCADE, "workerId" INTEGER NOT NULL REFERENCES "Worker"("id"), "salary" DECIMAL(14,2) NOT NULL, PRIMARY KEY ("shiftId", "workerId"));
CREATE TABLE "BarrelOperation" ("id" SERIAL PRIMARY KEY, "barrelId" INTEGER NOT NULL REFERENCES "Barrel"("id"), "type" "BarrelOperationType" NOT NULL, "date" TIMESTAMP(3) NOT NULL, "tons" DECIMAL(12,3) NOT NULL, "pricePerTon" DECIMAL(14,2), "amount" DECIMAL(14,2), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "CementSale" ("id" SERIAL PRIMARY KEY, "date" TIMESTAMP(3) NOT NULL, "client" TEXT NOT NULL, "bags" INTEGER NOT NULL, "pricePerBag" DECIMAL(14,2) NOT NULL, "amount" DECIMAL(14,2) NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "MaterialSale" ("id" SERIAL PRIMARY KEY, "date" TIMESTAMP(3) NOT NULL, "material" "Material" NOT NULL, "tons" DECIMAL(12,3) NOT NULL, "pricePerTon" DECIMAL(14,2) NOT NULL, "amount" DECIMAL(14,2) NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "Expense" ("id" SERIAL PRIMARY KEY, "date" TIMESTAMP(3) NOT NULL, "category" "ExpenseCategory" NOT NULL, "amount" DECIMAL(14,2) NOT NULL, "comment" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
INSERT INTO "Barrel" ("id", "name") VALUES (1, 'Бочка №1'), (2, 'Бочка №2');

