import { useEffect, useState, type FormEvent, type ReactNode } from 'react';
import { BarChart3, Boxes, Calculator, ChevronLeft, CircleDollarSign, Factory, Landmark, MoreVertical, PackagePlus, Plus, Receipt, ShoppingCart, Trash2, Users, WalletCards, X } from 'lucide-react';
import { api } from './api';
import { Analytics, ExpenseStats, Finance, MaterialStats, Operations, Production, StockSummary, WorkerStats } from './Reports';

type Page = 'home'|'shift'|'production'|'workers'|'cement'|'sales'|'materials'|'expenses'|'salary'|'finance'|'analytics'|'concrete'|'cash'|'history';
type Grade = 'M500'|'M600';
type GradeStock = { received:number;used:number;remaining:number };
type ProductStock = { produced:number;sold:number;remaining:number };
type Dashboard = { production:{bags:number;tons:number};workers:number;salary:number;sales:{cement:number;sand:number;gravel:number};expenses:number;finance:{revenue:number;costs:number;profit:number};cash:{balance:number;income:number;costs:number;since:string|null};stock:{bags:number;produced:number;sold:number;grades:Record<Grade,ProductStock>;monthRevenue:number} };
type Worker = { id:number;name:string;phone?:string;position:string;active:boolean };
type Barrel = { id:number;name:string;received:number;used:number;grades:Record<Grade,GradeStock>;activeGrade:Grade|null };
const rub = (v=0) => new Intl.NumberFormat('ru-RU',{style:'currency',currency:'RUB',maximumFractionDigits:0}).format(v);
const today = new Date().toISOString().slice(0,10);

function Card({title,value,sub,icon}:{title:string;value:string|number;sub?:string;icon:ReactNode}) { return <div className="card"><div className="card-icon">{icon}</div><div className="muted">{title}</div><strong>{value}</strong>{sub&&<small>{sub}</small>}</div> }
function BalanceCarousel({dash}:{dash:Dashboard}){return <><div className="balance-carousel"><section className="hero"><span>Прибыль сегодня</span><strong className={dash.finance.profit<0?'negative':''}>{rub(dash.finance.profit)}</strong><div><span>Доход {rub(dash.finance.revenue)}</span><span>Расход {rub(dash.finance.costs)}</span></div></section><section className="hero cash-slide"><span>Текущий баланс</span><strong className={dash.cash.balance<0?'negative':''}>{rub(dash.cash.balance)}</strong><div><span>Поступило {rub(dash.cash.income)}</span><span>Расход {rub(dash.cash.costs)}</span></div></section></div><div className="swipe-hint">Свайпните влево · прибыль / текущий баланс</div></>}
function Field({label,...props}:{label:string}&React.InputHTMLAttributes<HTMLInputElement>) { return <label><span>{label}</span><input {...props}/></label> }
function Select({label,children,...props}:{label:string;children:ReactNode}&React.SelectHTMLAttributes<HTMLSelectElement>) { return <label><span>{label}</span><select {...props}>{children}</select></label> }

export default function App(){
 const [page,setPage]=useState<Page>('home'),[dash,setDash]=useState<Dashboard|null>(null),[workers,setWorkers]=useState<Worker[]>([]),[barrels,setBarrels]=useState<Barrel[]>([]),[admin,setAdmin]=useState('Администратор'),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const load=async()=>{setLoading(true);try{const [d,w,b,me]=await Promise.all([api<Dashboard>('/dashboard'),api<Worker[]>('/workers'),api<Barrel[]>('/barrels'),api<{name:string}>('/auth/me')]);setDash(d);setWorkers(w);setBarrels(b);setAdmin(me.name);setError('')}catch(e){setError((e as Error).message)}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const done=()=>{window.Telegram?.WebApp.HapticFeedback?.notificationOccurred('success');setPage('home');load()};
 if(page!=='home') return <Shell title={titles[page]} back={()=>setPage('home')}>{page==='shift'?<Shift workers={workers.filter(w=>w.active)} barrels={barrels} done={done}/>:page==='production'?<Production reload={load}/>:page==='workers'?<Workers workers={workers} done={load}/>:page==='cement'?<Cement barrels={barrels} done={done}/>:page==='sales'?<><StockSummary/><Sale done={done}/><Operations kind="sales" reload={load}/></>:page==='materials'?<><MaterialStats/><MaterialSale done={done}/><Operations kind="materials" reload={load}/></>:page==='expenses'?<><ExpenseStats/><Expense done={done}/><Operations kind="expenses" reload={load}/></>:page==='salary'?<WorkerStats/>:page==='finance'?<Finance/>:page==='concrete'?<Concrete/>:page==='cash'?<Cash/>:page==='history'?<HistoricalBags/>:<Analytics/>}</Shell>;
 return <main><header><div><span className="eyebrow">{admin}</span><h1>Cement CRM</h1></div><div className="avatar">Ц</div></header>{error&&<div className="alert">{error}</div>}{loading&&!dash?<div className="loader">Загружаем данные…</div>:dash&&<><BalanceCarousel dash={dash}/><h2>Сегодня</h2><section className="grid"><Card icon={<Factory/>} title="Производство" value={`${dash.production.bags} меш.`} sub={`${dash.production.tons.toFixed(2)} т`}/><Card icon={<Users/>} title="Работники" value={dash.workers} sub={`Начислено ${rub(dash.salary)}`}/><Card icon={<ShoppingCart/>} title="Продажи" value={rub(dash.sales.cement+dash.sales.sand+dash.sales.gravel)} sub="Цемент и сыпучие"/><Card icon={<Receipt/>} title="Расходы" value={rub(dash.expenses)} sub="За текущий день"/></section><section className="grid stock-grid"><Card icon={<Factory/>} title="Нафасовано всего" value={`${dash.stock.produced} меш.`} sub={`М500: ${dash.stock.grades.M500.produced} · М600: ${dash.stock.grades.M600.produced}`}/><Card icon={<ShoppingCart/>} title="Продано всего" value={`${dash.stock.sold} меш.`} sub={`М500: ${dash.stock.grades.M500.sold} · М600: ${dash.stock.grades.M600.sold}`}/></section><section className="stock"><div><span>Остаток готовой продукции</span><strong>{dash.stock.bags} мешков</strong><small>М500: {dash.stock.grades.M500.remaining} · М600: {dash.stock.grades.M600.remaining}</small></div><Boxes/><div className="bar"><i style={{width:`${Math.min(100,dash.stock.bags/10)}%`}}/></div></section><h2>Быстрые действия</h2><nav className="actions"><button className="primary" onClick={()=>setPage('shift')}><Plus/>Новая смена</button><button className="primary sale-primary" onClick={()=>setPage('sales')}><ShoppingCart/>Продажа</button>{menu.map(x=><button key={x.page} onClick={()=>setPage(x.page)}>{x.icon}<span>{x.label}</span></button>)}</nav></>}</main>
}
const titles:Record<Exclude<Page,'home'>,string>={shift:'Новая смена',production:'Производство',workers:'Работники',cement:'Приход цемента',sales:'Продажа цемента',materials:'Сыпучие материалы',expenses:'Новый расход',salary:'Зарплата',finance:'Финансы',analytics:'Аналитика',concrete:'Бетон',cash:'Инкассация',history:'Стартовые данные'};
const menu:{page:Page;label:string;icon:ReactNode}[]=[{page:'production',label:'Производство',icon:<Factory/>},{page:'cement',label:'Цемент',icon:<PackagePlus/>},{page:'concrete',label:'Бетон',icon:<Calculator/>},{page:'cash',label:'Инкассация',icon:<Landmark/>},{page:'history',label:'До 23.07',icon:<Plus/>},{page:'workers',label:'Работники',icon:<Users/>},{page:'salary',label:'Зарплата',icon:<WalletCards/>},{page:'sales',label:'Продажи',icon:<ShoppingCart/>},{page:'materials',label:'Сыпучие',icon:<Boxes/>},{page:'expenses',label:'Расходы',icon:<Receipt/>},{page:'finance',label:'Финансы',icon:<Landmark/>},{page:'analytics',label:'Аналитика',icon:<BarChart3/>}];
function Shell({title,back,children}:{title:string;back:()=>void;children:ReactNode}){return <main><header className="sub"><button onClick={back}><ChevronLeft/></button><h1>{title}</h1><i/></header>{children}</main>}
function Form({children,onSubmit,submit='Сохранить'}:{children:ReactNode;onSubmit:(e:FormEvent<HTMLFormElement>)=>void;submit?:string}){return <form onSubmit={onSubmit}>{children}<button className="submit">{submit}</button></form>}
function useSubmit(done:()=>void){const [busy,setBusy]=useState(false),[error,setError]=useState(''); const run=async(path:string,data:FormData|Record<string,unknown>)=>{setBusy(true);setError('');try{const body=data instanceof FormData?Object.fromEntries(data):data;await api(path,{method:'POST',body:JSON.stringify(body)});done()}catch(e){setError((e as Error).message)}finally{setBusy(false)}};return{run,busy,error}}
function Shift({workers,barrels,done}:{workers:Worker[];barrels:Barrel[];done:()=>void}){const availableGrades=(['M500','M600'] as Grade[]).filter(g=>barrels.some(b=>b.activeGrade===g&&b.grades[g].remaining>0.0005));const [selected,setSelected]=useState<number[]>([]),[bags,setBags]=useState(0),[grade,setGrade]=useState<Grade>(availableGrades[0]??'M500');const {run,busy,error}=useSubmit(done);useEffect(()=>{window.scrollTo({top:0,behavior:'instant'})},[]);return <Form onSubmit={e=>{e.preventDefault();const obj=Object.fromEntries(new FormData(e.currentTarget));run('/shifts',{...obj,workerIds:selected})}}><Field label="Дата" name="date" type="date" defaultValue={today} required/><Select label="Марка цемента" name="grade" value={grade} onChange={e=>setGrade(e.target.value as Grade)}>{(['M500','M600'] as Grade[]).map(g=><option key={g} value={g} disabled={!availableGrades.includes(g)}>{g}{availableGrades.includes(g)?'':' · нет в бочках'}</option>)}</Select><Field label="Количество мешков" name="bags" type="number" min="1" onChange={e=>setBags(+e.target.value)} required/><div className="calculation"><span>Вес продукции</span><strong>{(bags*.025).toFixed(3)} т</strong></div><Field label="Погрузка сыпучих, тонн" name="loadingTons" type="number" step="0.001" defaultValue="0"/><Select label="Списать из бочки" name="barrelId" required><option value="">Выберите</option>{barrels.filter(b=>b.activeGrade===grade&&b.grades[grade].remaining>0.0005).map(b=><option key={b.id} value={b.id}>{b.name} · {b.grades[grade].remaining.toFixed(2)} т {grade}</option>)}</Select><div className="field-title">Работники</div><div className="checks">{workers.map(w=><button type="button" className={selected.includes(w.id)?'checked':''} onClick={()=>setSelected(s=>s.includes(w.id)?s.filter(id=>id!==w.id):[...s,w.id])} key={w.id}><i>{selected.includes(w.id)?'✓':''}</i><span>{w.name}<small>{w.position}</small></span></button>)}</div>{error&&<div className="alert">{error}</div>}{busy&&<small>Сохранение…</small>}</Form>}
function Workers({workers,done}:{workers:Worker[];done:()=>void}){const [open,setOpen]=useState(false),[editing,setEditing]=useState<Worker|null>(null);const close=()=>{setOpen(false);setEditing(null)};const save=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const body=JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)));await api(editing?`/workers/${editing.id}`:'/workers',{method:editing?'PATCH':'POST',body});close();done()};const deactivate=async(w:Worker)=>{if(!confirm(`Деактивировать ${w.name}?`))return;await api(`/workers/${w.id}`,{method:'DELETE'});done()};return <><button className="wide-add" onClick={()=>setOpen(true)}><Plus/>Добавить работника</button><div className="list">{workers.map(w=><button className="person person-button" onClick={()=>{setEditing(w);setOpen(true)}} key={w.id}><div className="avatar small">{w.name[0]}</div><div><strong>{w.name}</strong><small>{w.position}{w.phone?` · ${w.phone}`:''}</small></div><span className={w.active?'active':'inactive'}>{w.active?'Работает':'Неактивен'}</span></button>)}</div>{open&&<div className="modal"><div><button className="close" onClick={close}><X/></button><h2>{editing?'Работник':'Новый работник'}</h2><Form onSubmit={save} submit={editing?'Сохранить изменения':'Добавить'}><Field label="Имя" name="name" defaultValue={editing?.name} required/><Field label="Телефон" name="phone" type="tel" defaultValue={editing?.phone}/><Field label="Должность" name="position" defaultValue={editing?.position} required/></Form>{editing?.active&&<button className="deactivate" onClick={()=>deactivate(editing)}>Деактивировать работника</button>}</div></div>}</>}
type CementReceipt={id:number;barrelId:number;grade:Grade;date:string;tons:number;pricePerTon:number;barrel:{name:string}};
function Cement({barrels,done}:{barrels:Barrel[];done:()=>void}){
 const {run,busy,error}=useSubmit(done),[receipts,setReceipts]=useState<CementReceipt[]>([]),[editError,setEditError]=useState('');
 useEffect(()=>{api<CementReceipt[]>('/cement').then(setReceipts)},[]);
 const edit=async(x:CementReceipt)=>{const tons=prompt('Количество тонн',String(x.tons));if(tons===null)return;const pricePerTon=prompt('Цена за тонну',String(x.pricePerTon));if(pricePerTon===null)return;const grade=prompt('Марка цемента: M500 или M600',x.grade)?.toUpperCase();if(grade!=='M500'&&grade!=='M600')return setEditError('Укажите марку M500 или M600');const barrelId=prompt('Номер бочки: 1 — большая, 2 — маленькая',String(x.barrelId));if(barrelId===null)return;try{setEditError('');await api(`/cement/${x.id}`,{method:'PATCH',body:JSON.stringify({tons,pricePerTon,grade,barrelId,date:x.date.slice(0,10)})});done()}catch(e){setEditError((e as Error).message)}};
 return <><div className="grid barrel-grid">{barrels.map(b=>{const g=b.activeGrade;return <Card key={b.id} icon={<Boxes/>} title={b.name} value={`${g?b.grades[g].remaining.toFixed(2):'0.00'} т`} sub={g?`${g} · принято ${b.grades[g].received.toFixed(1)} · использовано ${b.grades[g].used.toFixed(1)}`:'Бочка пустая'}/>})}</div><Form onSubmit={e=>{e.preventDefault();run('/cement',new FormData(e.currentTarget))}}><Select label="Бочка" name="barrelId" required><option value="">Выберите бочку</option>{barrels.map(b=><option value={b.id} key={b.id}>{b.name}{b.activeGrade?` · сейчас ${b.activeGrade}`:' · пустая'}</option>)}</Select><Select label="Марка цемента" name="grade"><option value="M500">М500</option><option value="M600">М600</option></Select><Field label="Дата приёма" name="date" type="date" defaultValue={today} required/><Field label="Количество тонн" name="tons" type="number" min="0.001" step="0.001" required/><Field label="Цена за тонну" name="pricePerTon" type="number" min="0.01" step="0.01" required/>{error&&<div className="alert">{error}</div>}{busy&&<small>Сохраняем приход…</small>}</Form>{editError&&<div className="alert">{editError}</div>}<h2>История приходов</h2><div className="list">{receipts.map(x=><div className="history compact" key={x.id}><div><strong>{x.grade} · {Number(x.tons).toFixed(3)} т</strong><small>{new Date(x.date).toLocaleDateString('ru-RU')} · {barrels.find(b=>b.id===x.barrelId)?.name??x.barrel.name}</small></div><button className="icon-button" onClick={()=>edit(x)} title="Редактировать приход"><MoreVertical/></button></div>)}</div></>
}
function Sale({done}:{done:()=>void}){const {run,busy,error}=useSubmit(done);return <Form onSubmit={e=>{e.preventDefault();run('/sales',new FormData(e.currentTarget))}}><Field label="Дата" name="date" type="date" defaultValue={today} required/><Select label="Марка цемента" name="grade"><option value="M500">М500</option><option value="M600">М600</option></Select><Field label="Клиент (необязательно)" name="client"/><Field label="Количество мешков" name="bags" type="number" min="1" required/><Field label="Цена за мешок" name="pricePerBag" type="number" min="0.01" step="0.01" required/>{error&&<div className="alert">{error}</div>}{busy&&<small>Сохраняем продажу…</small>}</Form>}
function MaterialSale({done}:{done:()=>void}){const {run,error}=useSubmit(done);return <Form onSubmit={e=>{e.preventDefault();run('/materials',new FormData(e.currentTarget))}}><Field label="Дата" name="date" type="date" defaultValue={today} required/><Select label="Материал" name="material"><option value="SAND">Песок</option><option value="GRAVEL">Щебень</option></Select><Field label="Количество тонн" name="tons" type="number" step="0.001" required/><Field label="Цена за тонну" name="pricePerTon" type="number" step="0.01" required/><label className="finance-check"><input type="checkbox" name="includeInFinance"/><span>Учесть эту продажу в прибыли и текущей кассе</span></label><small className="cash-note">По умолчанию прибыль от сыпучих не учитывается.</small>{error&&<div className="alert">{error}</div>}</Form>}
function Expense({done}:{done:()=>void}){const {run,error}=useSubmit(done);return <Form onSubmit={e=>{e.preventDefault();run('/expenses',new FormData(e.currentTarget))}}><Field label="Дата" name="date" type="date" defaultValue={today} required/><Select label="Категория" name="category">{[['SALARY','Зарплата'],['RENT','Аренда'],['ELECTRICITY','Электричество'],['FUEL','Топливо'],['REPAIR','Ремонт'],['PACKAGING','Упаковка'],['OTHER','Прочее']].map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</Select><Field label="Сумма" name="amount" type="number" step="0.01" required/><Field label="Комментарий" name="comment"/>{error&&<div className="alert">{error}</div>}</Form>}
function Salary(){const [rows,setRows]=useState<{worker:string;shifts:number;tons:number;salary:number}[]>([]);useEffect(()=>{api<typeof rows>('/salary').then(setRows)},[]);return <><div className="summary"><CircleDollarSign/><span>Начислено за месяц</span><strong>{rub(rows.reduce((s,x)=>s+x.salary,0))}</strong></div><div className="list">{rows.map(r=><div className="salary-row" key={r.worker}><div><strong>{r.worker}</strong><small>{r.shifts} смен · {r.tons.toFixed(2)} т</small></div><b>{rub(r.salary)}</b></div>)}{!rows.length&&<div className="empty"><BarChart3/>Начислений пока нет</div>}</div></>}

type ConcreteNorm={id:number;name:string;grade:Grade;cementKgPerM3:number};
function Concrete(){
 const [rows,setRows]=useState<ConcreteNorm[]>([]),[editing,setEditing]=useState<ConcreteNorm|null>(null),[volume,setVolume]=useState(1),[grade,setGrade]=useState<Grade>('M500'),[concrete,setConcrete]=useState('М100'),[error,setError]=useState('');
 const load=()=>api<ConcreteNorm[]>('/concrete').then(setRows);useEffect(()=>{load()},[]);
 const available=rows.filter(x=>x.grade===grade),selected=available.find(x=>x.name===concrete)??available[0];
 const save=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setError('');try{const body=JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)));await api(editing?`/concrete/${editing.id}`:'/concrete',{method:editing?'PATCH':'POST',body});setEditing(null);(e.currentTarget as HTMLFormElement).reset();load()}catch(x){setError((x as Error).message)}};
 const remove=async(id:number)=>{if(!confirm('Удалить эту норму бетона?'))return;await api(`/concrete/${id}`,{method:'DELETE'});load()};
 return <><section className="concrete-calculator"><Select label="Марка цемента" value={grade} onChange={e=>{setGrade(e.target.value as Grade);setConcrete('М100')}}><option value="M500">М500</option><option value="M600">М600</option></Select><Select label="Марка бетона" value={selected?.name??''} onChange={e=>setConcrete(e.target.value)}>{available.map(x=><option key={x.id}>{x.name}</option>)}</Select><Field label="Объём бетона, м³" type="number" min="0.001" step="0.001" value={volume} onChange={e=>setVolume(Math.max(0,+e.target.value))}/><div className="summary"><Calculator/><span>Расход цемента</span><strong>{selected?(Number(selected.cementKgPerM3)*volume).toFixed(1):'0'} кг</strong><small>{selected?`${Number(selected.cementKgPerM3)} кг на 1 м³`:''}</small></div></section><h2>Нормы</h2><div className="list concrete-list">{available.map(x=><div className="history compact" key={x.id}><button className="norm-main" onClick={()=>setEditing(x)}><strong>{x.name} · {x.grade}</strong><small>{Number(x.cementKgPerM3)} кг/м³</small></button><button className="icon-button danger" onClick={()=>remove(x.id)}><Trash2/></button></div>)}</div><h2>{editing?'Изменить норму':'Добавить свою норму'}</h2><Form onSubmit={save} submit={editing?'Сохранить норму':'Добавить норму'}><Field label="Марка бетона" name="name" placeholder="Например, М450" defaultValue={editing?.name} required/><Select label="Марка цемента" name="grade" defaultValue={editing?.grade??grade}><option value="M500">М500</option><option value="M600">М600</option></Select><Field label="Норма цемента, кг на 1 м³" name="cementKgPerM3" type="number" min="0.01" step="0.01" defaultValue={editing?.cementKgPerM3} required/>{error&&<div className="alert">{error}</div>}</Form>{editing&&<button className="wide-add" onClick={()=>setEditing(null)}>Отменить редактирование</button>}</>
}

type CashData={balance:number;income:number;costs:number;since:string|null;collections:{id:number;amount:number;createdAt:string}[]};
function Cash(){const [data,setData]=useState<CashData|null>(null),[error,setError]=useState('');const load=()=>api<CashData>('/cash').then(setData).catch(x=>setError(x.message));useEffect(()=>{load()},[]);const collect=async()=>{if(!data||data.balance<=0||!confirm(`Провести инкассацию на ${rub(data.balance)}?`))return;try{await api('/cash/collect',{method:'POST',body:'{}'});window.Telegram?.WebApp.HapticFeedback?.notificationOccurred('success');load()}catch(x){setError((x as Error).message)}};if(!data)return <div className="loader">Считаем кассу…</div>;return <><section className="hero"><span>Действующий баланс</span><strong className={data.balance<0?'negative':''}>{rub(data.balance)}</strong><div><span>Поступило {rub(data.income)}</span><span>Расход {rub(data.costs)}</span></div></section>{error&&<div className="alert">{error}</div>}<button className="submit collection-wide" disabled={data.balance<=0} onClick={collect}>Инкассация</button><small className="cash-note">Инкассация обнулит только действующий баланс. Общая аналитика доходов и расходов сохранится.</small><h2>История инкассаций</h2><div className="list">{data.collections.map(x=><div className="history compact" key={x.id}><div><strong>{rub(Number(x.amount))}</strong><small>{new Date(x.createdAt).toLocaleString('ru-RU')}</small></div></div>)}{!data.collections.length&&<div className="empty">Инкассаций пока не было</div>}</div></>}

type HistoricalEntry={id:number;date:string;grade:Grade;producedBags:number;soldBags:number};
function HistoricalBags(){const [rows,setRows]=useState<HistoricalEntry[]>([]),[error,setError]=useState('');const load=()=>api<HistoricalEntry[]>('/historical-bags').then(setRows);useEffect(()=>{load()},[]);const save=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setError('');try{await api('/historical-bags',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});load()}catch(x){setError((x as Error).message)}};const remove=async(id:number)=>{if(!confirm('Удалить стартовые данные за этот день?'))return;await api(`/historical-bags/${id}`,{method:'DELETE'});load()};return <><div className="alert info-note">Временный раздел для показателей до 23.07. Приход и расход цемента в бочках эти записи не изменяют.</div><Form onSubmit={save} submit="Сохранить данные за день"><Field label="Дата" name="date" type="date" max="2026-07-23" required/><Select label="Марка цемента" name="grade"><option value="M500">М500</option><option value="M600">М600</option></Select><Field label="Нафасовано, мешков" name="producedBags" type="number" min="0" step="1" defaultValue="0" required/><Field label="Продано, мешков" name="soldBags" type="number" min="0" step="1" defaultValue="0" required/>{error&&<div className="alert">{error}</div>}</Form><h2>Внесённые дни</h2><div className="list">{rows.map(x=><div className="history compact" key={x.id}><div><strong>{new Date(x.date).toLocaleDateString('ru-RU')} · {x.grade}</strong><small>Нафасовано {x.producedBags} · продано {x.soldBags}</small></div><button className="icon-button danger" onClick={()=>remove(x.id)}><Trash2/></button></div>)}</div></>}
