import { useEffect, useState, type FormEvent, type ReactNode } from 'react';
import { BarChart3, Boxes, ChevronLeft, CircleDollarSign, Factory, Landmark, PackagePlus, Plus, Receipt, ShoppingCart, Users, WalletCards, X } from 'lucide-react';
import { api } from './api';
import { Analytics, ExpenseStats, Finance, MaterialStats, Operations, Production, StockSummary, WorkerStats } from './Reports';

type Page = 'home'|'shift'|'production'|'workers'|'cement'|'sales'|'materials'|'expenses'|'salary'|'finance'|'analytics';
type Dashboard = { production:{bags:number;tons:number};workers:number;salary:number;sales:{cement:number;sand:number;gravel:number};expenses:number;finance:{revenue:number;costs:number;profit:number};stock:{bags:number;monthRevenue:number} };
type Worker = { id:number;name:string;phone?:string;position:string;active:boolean };
type Barrel = { id:number;name:string;received:number;used:number };
const rub = (v=0) => new Intl.NumberFormat('ru-RU',{style:'currency',currency:'RUB',maximumFractionDigits:0}).format(v);
const today = new Date().toISOString().slice(0,10);

function Card({title,value,sub,icon}:{title:string;value:string|number;sub?:string;icon:ReactNode}) { return <div className="card"><div className="card-icon">{icon}</div><div className="muted">{title}</div><strong>{value}</strong>{sub&&<small>{sub}</small>}</div> }
function Field({label,...props}:{label:string}&React.InputHTMLAttributes<HTMLInputElement>) { return <label><span>{label}</span><input {...props}/></label> }
function Select({label,children,...props}:{label:string;children:ReactNode}&React.SelectHTMLAttributes<HTMLSelectElement>) { return <label><span>{label}</span><select {...props}>{children}</select></label> }

export default function App(){
 const [page,setPage]=useState<Page>('home'),[dash,setDash]=useState<Dashboard|null>(null),[workers,setWorkers]=useState<Worker[]>([]),[barrels,setBarrels]=useState<Barrel[]>([]),[admin,setAdmin]=useState('Администратор'),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const load=async()=>{setLoading(true);try{const [d,w,b,me]=await Promise.all([api<Dashboard>('/dashboard'),api<Worker[]>('/workers'),api<Barrel[]>('/barrels'),api<{name:string}>('/auth/me')]);setDash(d);setWorkers(w);setBarrels(b);setAdmin(me.name);setError('')}catch(e){setError((e as Error).message)}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const done=()=>{window.Telegram?.WebApp.HapticFeedback?.notificationOccurred('success');setPage('home');load()};
 if(page!=='home') return <Shell title={titles[page]} back={()=>setPage('home')}>{page==='shift'?<Shift workers={workers.filter(w=>w.active)} barrels={barrels} done={done}/>:page==='production'?<Production reload={load}/>:page==='workers'?<Workers workers={workers} done={load}/>:page==='cement'?<Cement barrels={barrels} done={done}/>:page==='sales'?<><StockSummary/><Sale done={done}/><Operations kind="sales" reload={load}/></>:page==='materials'?<><MaterialStats/><MaterialSale done={done}/><Operations kind="materials" reload={load}/></>:page==='expenses'?<><ExpenseStats/><Expense done={done}/><Operations kind="expenses" reload={load}/></>:page==='salary'?<WorkerStats/>:page==='finance'?<Finance/>:<Analytics/>}</Shell>;
 return <main><header><div><span className="eyebrow">{admin}</span><h1>Cement CRM</h1></div><div className="avatar">Ц</div></header>{error&&<div className="alert">{error}</div>}{loading&&!dash?<div className="loader">Загружаем данные…</div>:dash&&<><section className="hero"><span>Прибыль сегодня</span><strong className={dash.finance.profit<0?'negative':''}>{rub(dash.finance.profit)}</strong><div><span>Доход {rub(dash.finance.revenue)}</span><span>Расход {rub(dash.finance.costs)}</span></div></section><h2>Сегодня</h2><section className="grid"><Card icon={<Factory/>} title="Производство" value={`${dash.production.bags} меш.`} sub={`${dash.production.tons.toFixed(2)} т`}/><Card icon={<Users/>} title="Работники" value={dash.workers} sub={`Начислено ${rub(dash.salary)}`}/><Card icon={<ShoppingCart/>} title="Продажи" value={rub(dash.sales.cement+dash.sales.sand+dash.sales.gravel)} sub="Цемент и сыпучие"/><Card icon={<Receipt/>} title="Расходы" value={rub(dash.expenses)} sub="За текущий день"/></section><section className="stock"><div><span>Готовая продукция</span><strong>{dash.stock.bags} мешков</strong></div><Boxes/><div className="bar"><i style={{width:`${Math.min(100,dash.stock.bags/10)}%`}}/></div></section><h2>Быстрые действия</h2><nav className="actions"><button className="primary" onClick={()=>setPage('shift')}><Plus/>Новая смена</button>{menu.map(x=><button key={x.page} onClick={()=>setPage(x.page)}>{x.icon}<span>{x.label}</span></button>)}</nav></>}</main>
}
const titles:Record<Exclude<Page,'home'>,string>={shift:'Новая смена',production:'Производство',workers:'Работники',cement:'Приход цемента',sales:'Продажа цемента',materials:'Сыпучие материалы',expenses:'Новый расход',salary:'Зарплата',finance:'Финансы',analytics:'Аналитика'};
const menu:{page:Page;label:string;icon:ReactNode}[]=[{page:'production',label:'Производство',icon:<Factory/>},{page:'cement',label:'Цемент',icon:<PackagePlus/>},{page:'workers',label:'Работники',icon:<Users/>},{page:'salary',label:'Зарплата',icon:<WalletCards/>},{page:'sales',label:'Продажи',icon:<ShoppingCart/>},{page:'materials',label:'Сыпучие',icon:<Boxes/>},{page:'expenses',label:'Расходы',icon:<Receipt/>},{page:'finance',label:'Финансы',icon:<Landmark/>},{page:'analytics',label:'Аналитика',icon:<BarChart3/>}];
function Shell({title,back,children}:{title:string;back:()=>void;children:ReactNode}){return <main><header className="sub"><button onClick={back}><ChevronLeft/></button><h1>{title}</h1><i/></header>{children}</main>}
function Form({children,onSubmit,submit='Сохранить'}:{children:ReactNode;onSubmit:(e:FormEvent<HTMLFormElement>)=>void;submit?:string}){return <form onSubmit={onSubmit}>{children}<button className="submit">{submit}</button></form>}
function useSubmit(done:()=>void){const [busy,setBusy]=useState(false),[error,setError]=useState(''); const run=async(path:string,data:FormData)=>{setBusy(true);try{await api(path,{method:'POST',body:JSON.stringify(Object.fromEntries(data))});done()}catch(e){setError((e as Error).message)}finally{setBusy(false)}};return{run,busy,error}}
function Shift({workers,barrels,done}:{workers:Worker[];barrels:Barrel[];done:()=>void}){const [selected,setSelected]=useState<number[]>([]),[bags,setBags]=useState(0);const {run,busy,error}=useSubmit(done);return <Form onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);d.set('workerIds',JSON.stringify(selected));const obj=Object.fromEntries(d);api('/shifts',{method:'POST',body:JSON.stringify({...obj,workerIds:selected})}).then(done).catch(x=>alert(x.message))}}><Field label="Дата" name="date" type="date" defaultValue={today} required/><Field label="Количество мешков" name="bags" type="number" min="1" onChange={e=>setBags(+e.target.value)} required/><div className="calculation"><span>Вес продукции</span><strong>{(bags*.025).toFixed(3)} т</strong></div><Field label="Погрузка сыпучих, тонн" name="loadingTons" type="number" step="0.001" defaultValue="0"/><Select label="Списать из бочки" name="barrelId" required><option value="">Выберите</option>{barrels.map(b=><option key={b.id} value={b.id}>{b.name} · {(b.received-b.used).toFixed(2)} т</option>)}</Select><div className="field-title">Работники</div><div className="checks">{workers.map(w=><button type="button" className={selected.includes(w.id)?'checked':''} onClick={()=>setSelected(s=>s.includes(w.id)?s.filter(id=>id!==w.id):[...s,w.id])} key={w.id}><i>{selected.includes(w.id)?'✓':''}</i><span>{w.name}<small>{w.position}</small></span></button>)}</div>{error&&<div className="alert">{error}</div>}{busy&&<small>Сохранение…</small>}</Form>}
function Workers({workers,done}:{workers:Worker[];done:()=>void}){const [open,setOpen]=useState(false),[editing,setEditing]=useState<Worker|null>(null);const close=()=>{setOpen(false);setEditing(null)};const save=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const body=JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)));await api(editing?`/workers/${editing.id}`:'/workers',{method:editing?'PATCH':'POST',body});close();done()};const deactivate=async(w:Worker)=>{if(!confirm(`Деактивировать ${w.name}?`))return;await api(`/workers/${w.id}`,{method:'DELETE'});done()};return <><button className="wide-add" onClick={()=>setOpen(true)}><Plus/>Добавить работника</button><div className="list">{workers.map(w=><button className="person person-button" onClick={()=>{setEditing(w);setOpen(true)}} key={w.id}><div className="avatar small">{w.name[0]}</div><div><strong>{w.name}</strong><small>{w.position}{w.phone?` · ${w.phone}`:''}</small></div><span className={w.active?'active':'inactive'}>{w.active?'Работает':'Неактивен'}</span></button>)}</div>{open&&<div className="modal"><div><button className="close" onClick={close}><X/></button><h2>{editing?'Работник':'Новый работник'}</h2><Form onSubmit={save} submit={editing?'Сохранить изменения':'Добавить'}><Field label="Имя" name="name" defaultValue={editing?.name} required/><Field label="Телефон" name="phone" type="tel" defaultValue={editing?.phone}/><Field label="Должность" name="position" defaultValue={editing?.position} required/></Form>{editing?.active&&<button className="deactivate" onClick={()=>deactivate(editing)}>Деактивировать работника</button>}</div></div>}</>}
function Cement({barrels,done}:{barrels:Barrel[];done:()=>void}){const {run,error}=useSubmit(done);return <><div className="grid barrel-grid">{barrels.map(b=><Card key={b.id} icon={<Boxes/>} title={b.name} value={`${(b.received-b.used).toFixed(2)} т`} sub={`Принято ${b.received.toFixed(1)} · использовано ${b.used.toFixed(1)}`}/>)}</div><Form onSubmit={e=>{e.preventDefault();run('/cement',new FormData(e.currentTarget))}}><Select label="Бочка" name="barrelId" required>{barrels.map(b=><option value={b.id} key={b.id}>{b.name}</option>)}</Select><Field label="Дата приёма" name="date" type="date" defaultValue={today} required/><Field label="Количество тонн" name="tons" type="number" step="0.001" required/><Field label="Цена за тонну" name="pricePerTon" type="number" step="0.01" required/>{error&&<div className="alert">{error}</div>}</Form></>}
function Sale({done}:{done:()=>void}){const {run,error}=useSubmit(done);return <Form onSubmit={e=>{e.preventDefault();run('/sales',new FormData(e.currentTarget))}}><Field label="Дата" name="date" type="date" defaultValue={today} required/><Field label="Клиент" name="client" required/><Field label="Количество мешков" name="bags" type="number" min="1" required/><Field label="Цена за мешок" name="pricePerBag" type="number" step="0.01" required/>{error&&<div className="alert">{error}</div>}</Form>}
function MaterialSale({done}:{done:()=>void}){const {run,error}=useSubmit(done);return <Form onSubmit={e=>{e.preventDefault();run('/materials',new FormData(e.currentTarget))}}><Field label="Дата" name="date" type="date" defaultValue={today} required/><Select label="Материал" name="material"><option value="SAND">Песок</option><option value="GRAVEL">Щебень</option></Select><Field label="Количество тонн" name="tons" type="number" step="0.001" required/><Field label="Цена за тонну" name="pricePerTon" type="number" step="0.01" required/>{error&&<div className="alert">{error}</div>}</Form>}
function Expense({done}:{done:()=>void}){const {run,error}=useSubmit(done);return <Form onSubmit={e=>{e.preventDefault();run('/expenses',new FormData(e.currentTarget))}}><Field label="Дата" name="date" type="date" defaultValue={today} required/><Select label="Категория" name="category">{[['SALARY','Зарплата'],['RENT','Аренда'],['ELECTRICITY','Электричество'],['FUEL','Топливо'],['REPAIR','Ремонт'],['PACKAGING','Упаковка'],['OTHER','Прочее']].map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</Select><Field label="Сумма" name="amount" type="number" step="0.01" required/><Field label="Комментарий" name="comment"/>{error&&<div className="alert">{error}</div>}</Form>}
function Salary(){const [rows,setRows]=useState<{worker:string;shifts:number;tons:number;salary:number}[]>([]);useEffect(()=>{api<typeof rows>('/salary').then(setRows)},[]);return <><div className="summary"><CircleDollarSign/><span>Начислено за месяц</span><strong>{rub(rows.reduce((s,x)=>s+x.salary,0))}</strong></div><div className="list">{rows.map(r=><div className="salary-row" key={r.worker}><div><strong>{r.worker}</strong><small>{r.shifts} смен · {r.tons.toFixed(2)} т</small></div><b>{rub(r.salary)}</b></div>)}{!rows.length&&<div className="empty"><BarChart3/>Начислений пока нет</div>}</div></>}
